spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/security/**
          filters:
            - AuthenticationFilter

  application:
    name: GATEWAY-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/